meta_product_name: "Dished!"
meta_title: "Dished! Making dinner time easier"
meta_description: "A recipe inspiration platform for foodies and their friends"
meta_image: "cover.png" # should exist in `app/assets/images/`
